version: '2'

services:
  postgres:
    image: postgres:9.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=dev

volumes:
  pgdata:
    driver: local

